### ISSUE TITLE
Ошибка при запуске мастера настройки

### ISSUE THREAD

**Issue by vladimir1408v** [malinovsku/ha-keenetic_api#3]
Регистратор: homeassistant.loader
Источник: loader.py:1025
Первое сообщение: 02:06:58 (2 сообщений)
Последнее сообщение: 02:07:16

Unexpected exception importing platform custom_components.keenetic_api.config_flow
Traceback (most recent call last):
  File "/opt/lib/python3.11/site-packages/homeassistant/loader.py", line 1025, in _load_platform
  File "/opt/lib/python3.11/site-packages/homeassistant/loader.py", line 1058, in _import_platform
  File "/opt/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/var/lib/homeassistant/custom_components/keenetic_api/config_flow.py", line 86, in <module>
    class OptionsFlow(config_entries.OptionsFlow):
  File "/opt/var/lib/homeassistant/custom_components/keenetic_api/config_flow.py", line 96, in OptionsFlow
    ) -> config_entries.ConfigFlowResult:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.config_entries' has no attribute 'ConfigFlowResult'

Помогите пожалуйста, попробовал все доступные версии компонента, везде такая ошибка. Очень интересная интеграция, но не получается настроить

**Comment by vladimir1408v** [comment]
Замени в файле config_flow.py
Строки
config_entries.ConfigFlowResult
на
config_entries.FlowResult

и заработало, уважаемый разработчик, чем это грозит?

**Comment by malinovsku** [comment]
@vladimir1408v Актуальна ли проблема в версии [0.11](https://github.com/malinovsku/ha-keenetic_api/releases/tag/0.11) ?
